#! /bin/sh

sxhkd -m 1 &
$HOME/.bin/dual.sh
bspc monitor eDP1 -d 1 2 3
bspc monitor DP2-3 -d 4 5 6
bspc config border_width 2
bspc config split_ratio 0.5
bspc config window_gap 0
bspc config focus_follows_pointer true
bspc config focused_border_color "#FF0000"
